version: "3.9"

services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5433:5432
    volumes:
      - explorer_data:/var/lib/postgresql/data
      - ./explorer/src/explorer-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=explorer

  angular:
    build: ../soa-front-end/Explorer
    ports:
      - "4200:80"

  explorer:
    volumes:
      - ./explorer/src:/home/explorer/src
    build: ./explorer
    restart: on-failure
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: root
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
      ENCOUNTER_HOST: encounter
      ENCOUNTER_PORT: 8089
      TOUR_HOST: tour
      TOUR_PORT: 8080
    depends_on:
      - postgres

  encounter:
    build: ./encounter
    environment:
      - PORT=8089
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_DATABASE=explorer
      - DB_HOST=postgres
    volumes:
      - ./encounter:/home/node/app
    depends_on:
      - postgres

  tour:
    build: ./tour
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_DATABASE=explorer
      - DB_HOST=postgres
    depends_on:
      - postgres

volumes:
  explorer_data:
    driver: local
