version: "3.9"

services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5433:5432
    volumes:
      - explorer_data:/var/lib/postgresql/data
      - ./explorer/src/explorer-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=explorer

  angular:
    build: ../soa-front-end/Explorer
    ports:
      - "4200:80"

  explorer:
    volumes:
      - ./explorer/src:/home/explorer/src
    build: ./explorer
    restart: on-failure
    ports:
      - "44333:80"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: root
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
      ENCOUNTER_HOST: encounter
      ENCOUNTER_PORT: 8089
      TOUR_HOST: tour
      TOUR_PORT: 8080
    depends_on:
      - postgres

  encounter:
    build: ./encounter
    environment:
      - PORT=8089
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_DATABASE=explorer
      - DB_HOST=postgres
    volumes:
      - ./encounter:/home/node/app
    depends_on:
      - postgres

  follow:
    build: ./follow
    environment:
      - PORT=8089
      - NEO4J_DATABASE_PASSWORD=12345678
      - NEO4J_DATABASE_USERNAME=neo4j
      - NEO4J_DATABASE_URL=bolt://neo4j:7687
    volumes:
      - ./follow:/home/node/app
    depends_on:
      - neo4j

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  tour:
    build: ./tour
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_DATABASE=explorer
      - DB_HOST=postgres
    depends_on:
      - postgres

volumes:
  explorer_data:
    driver: local
