version: "3.7"
volumes:
    prometheus-data:
        driver: local
    grafana-data:
        driver: local
services:
    grafana:
        image: docker.io/grafana/grafana-oss:11.0.0
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana-data:/var/lib/grafana
        restart: unless-stopped
    prometheus:
        image: docker.io/prom/prometheus:v2.52.0
        container_name: prometheus
        ports:
            - 9090:9090
        command: "--config.file=/etc/prometheus/prometheus.yaml"
        volumes:
            - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
            - prometheus-data:/prometheus
        restart: unless-stopped
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4317:4317"
            - "55681:55681"
            - "55682:55682"
