version: "3.7"
volumes:
    prometheus-data:
        driver: local
    grafana:
        name: grafana
services:
    grafana:
        image: grafana/grafana:8.5.3
        ports:
            - "3000:3000"
        environment:
            GF_RENDERING_SERVER_URL: http://renderer:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            GF_LOG_FILTERS: rendering:debug
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/provisioning:/etc/grafana/provisioning
    prometheus:
        image: docker.io/prom/prometheus:v2.52.0
        container_name: prometheus
        ports:
            - 9090:9090
        command: "--config.file=/etc/prometheus/prometheus.yaml"
        volumes:
            - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
            - prometheus-data:/prometheus
        restart: unless-stopped

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        container_name: cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        devices:
            - /dev/kmsg
        privileged: true
        restart: unless-stopped

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4317:4317"
            - "55681:55681"
            - "55682:55682"
